rootProject.name = "JarvisMerged"
include(":app")
include(":modules:core")
include(":modules:engine")
include(":modules:automation")
include(":modules:llm")
include(":modules:smart")
include(":modules:ui")
include(":modules:features:device")
include(":modules:features:media")
include(":modules:features:vision")
include(":modules:features:monitoring")
